import {StyleSheet,Platform} from 'react-native';
import {Font,Spacing,Radius} from '../../theme';
export const messageBubbleStyles = StyleSheet.create({
  stickerBubble: {
    backgroundColor: 'transparent',
    borderWidth: 0,
    elevation: 0,
    paddingTop: 0,
    paddingHorizontal: 4,
    paddingBottom: 2,
  },
  bubbleRow: { marginBottom: 6 },
  bubbleRowRight: { alignItems: 'flex-end' },
  bubbleRowLeft: { alignItems: 'flex-start' },
  bubble: {
    minWidth: 96,
    paddingHorizontal: 10,
    paddingTop: 6,
    paddingBottom: Spacing.xs,
    borderRadius: Radius.lg,
    borderWidth: 1,
    elevation: 2,
  },
  bubbleSent: { borderBottomRightRadius: Radius.xs ?? 4 },
  bubbleReceived: { borderBottomLeftRadius: Radius.xs ?? 4 },
  senderName: {
    fontSize: Font.size.xs,
    marginBottom: 2,
    fontWeight: '700',
    letterSpacing: 0.5,
  },
  messageText: { fontSize: Font.size.md, lineHeight: 22, letterSpacing: 0.2 },
  metaRow: {
    flexDirection: 'row',
    alignItems: 'center',
    justifyContent: 'flex-end',
    marginTop: 3,
    gap: 4,
  },
  timeText: { fontSize: 10, letterSpacing: 0.3 },
  statusIcon: { fontSize: 10 },
  transferError: { fontSize: 11, lineHeight: 15, marginTop: 5, fontWeight: '600' },
  imageBubble: {
    width: 220,
    height: 220,
    borderRadius: Radius.sm,
    backgroundColor: '#0002',
  },
  sharedFile: {
    flexDirection: 'row',
    alignItems: 'center',
    minWidth: 220,
    maxWidth: 280,
    borderWidth: 1,
    borderRadius: Radius.sm,
    padding: Spacing.sm,
  },
  sharedFileIcon: {
    width: 42,
    height: 42,
    borderRadius: Radius.sm,
    alignItems: 'center',
    justifyContent: 'center',
    marginRight: Spacing.sm,
  },
  sharedFileInfo: { flex: 1, minWidth: 0, paddingRight: Spacing.xs },
  sharedFileTitle: { fontSize: Font.size.sm, fontWeight: '700' },
  sharedFileHint: { fontSize: Font.size.xs, marginTop: 3 },
  mediaPlaceholder: { alignItems: 'center', justifyContent: 'center', gap: Spacing.sm },
  mediaPlaceholderText: { fontSize: Font.size.sm, letterSpacing: 0.3 },
  mediaOverlay: {
    ...StyleSheet.absoluteFillObject,
    alignItems: 'center',
    justifyContent: 'center',
    gap: Spacing.xs,
    backgroundColor: 'rgba(0,0,0,0.35)',
    borderRadius: Radius.sm,
  },
  mediaOverlayText: { color: '#fff', fontSize: Font.size.sm, letterSpacing: 0.3 },
  deletedText: { fontSize: Font.size.sm, fontStyle: 'italic', flexShrink: 1 },
  // Constrain against the full row, not an already content-sized touch target.
  // The latter can clip the last word after Android measures wrapped text.
  bubbleTouchTarget: { maxWidth: '80%' },
  bubbleWrap: { minWidth: 0 },
  bubbleWrapWithReactions: { paddingBottom: 12 },
  reactionsOverlay: {
    position: 'absolute',
    bottom: 0,
    flexDirection: 'row',
    flexWrap: 'wrap',
    gap: 4,
  },
  reactionsOverlayLeft: { left: 8 },
  reactionBadge: {
    flexDirection: 'row',
    alignItems: 'center',
    paddingHorizontal: 7,
    paddingVertical: 2,
    borderRadius: Radius.pill,
    borderWidth: 1,
    shadowOpacity: 0.3,
    shadowRadius: 4,
    shadowOffset: { width: 0, height: 1 },
    elevation: 2,
  },
  reactionBadgeText: { fontSize: 13, lineHeight: 18, fontWeight: '700', marginLeft: 3 },
  reactionEmojiInBadge: { fontSize: 13, lineHeight: 18 },
  swipeReplyHint: {
    width: 48,
    justifyContent: 'center',
    alignItems: 'center',
    paddingLeft: Spacing.sm,
  },
  quoteBlock: {
    borderLeftWidth: 3,
    paddingLeft: Spacing.sm,
    paddingVertical: 4,
    paddingRight: Spacing.sm,
    marginBottom: 6,
    borderRadius: 4,
  },
  quoteName: { fontSize: Font.size.xs, fontWeight: '700', letterSpacing: 0.3 },
  quoteText: { fontSize: Font.size.xs, marginTop: 1 },
});
