const test=require('node:test'),assert=require('node:assert/strict'),fs=require('node:fs'),ts=require('typescript');
const out={};new Function('require','exports',ts.transpileModule(fs.readFileSync('src/services/identity/rememberedNeurons.ts','utf8'),{compilerOptions:{module:1,target:9}}).outputText)(()=>({validAccountId:id=>/^axonic:1:[a-f0-9]{64}$/.test(id)}),out);
const owner='axonic:1:'+'a'.repeat(64),other='axonic:1:'+'b'.repeat(64);
function fixture(){let clock=100000,fail=false;const rows=new Map(),cache=out.createRememberedNeurons({now:()=>clock,read:async id=>rows.get(id)??null,write:async(id,raw)=>{if(fail)throw Error('disk');rows.set(id,raw);}});return{cache,rows,advance:n=>clock+=n,fail:()=>fail=true};}
const peer=(endpoint='axon-lan://192.168.1.42:18080',account=other)=>({account,endpoint,route:'lan',expiresAt:120000});
test('authenticated private locator survives cache recreation with a bounded lifetime',async()=>{const f=fixture();await f.cache.remember(owner,peer());const list=await f.cache.list(owner);assert.equal(list.length,1);assert.equal(list[0].route,'private');assert.equal(list[0].expiresAt,100000+86400000);f.advance(86400001);assert.deepEqual(await f.cache.list(owner),[]);});
test('public, loopback, RTC, invalid IPv4/port and self locators are never cached',async()=>{const f=fixture();for(const address of ['axon-lan://8.8.8.8:80','axon-lan://127.0.0.1:80','axon-lan://10.999.1.1:80','axon-lan://10.0.0.1:65536','rtc:via','https://host/v2/axon'])await f.cache.remember(owner,peer(address));await f.cache.remember(owner,peer('axon-lan://10.0.0.1:80',owner));assert.deepEqual(await f.cache.list(owner),[]);});
test('private/VPN and carrier-grade addresses are accepted; bound is sixteen and ownership stays separate',async()=>{const f=fixture();for(let i=1;i<20;i++)await f.cache.remember(owner,peer('axon-lan://100.64.1.'+i+':18080','axonic:1:'+i.toString(16).padStart(64,'0')));assert.equal((await f.cache.list(owner)).length,16);assert.deepEqual(await f.cache.list(other),[]);});
test('corrupt, foreign and future cache data cannot manufacture trusted addresses; failed writes keep saved data',async()=>{const f=fixture();await f.cache.remember(owner,peer());const before=f.rows.get(owner);f.fail();await assert.rejects(f.cache.remember(owner,peer('axon-lan://10.0.0.2:80')),/disk/);assert.equal(f.rows.get(owner),before);for(const raw of ['broken',JSON.stringify({owner:other,peers:[]}),JSON.stringify({owner,peers:[{account:other,endpoint:'axon-lan://10.0.0.1:80',seen:200000}]})]){f.rows.set(owner,raw);assert.deepEqual(await f.cache.list(owner),[]);}});
