const test=require('node:test'),assert=require('node:assert/strict'),crypto=require('node:crypto');
const {load,fixture,now}=require('./helpers/attachment.cjs'),chat=load('rootChatLedger'),groups=load('rootGroups'),protocol=load('attachmentProtocol');
const key=()=>crypto.randomBytes(32).toString('hex');
const view=load('rootChatActions').rootChatView;

test('local group chat deletion keeps membership and direct history; a new group message reopens it',async()=>{
 const f=setup(),g=await f.group();await f.apis[0].enqueueGroup(g,key(),'old group text');await f.deliver(0,1);
 await f.apis[1].enqueue(f.accounts[0],key(),'private text');
 await f.apis[1].deleteChats(['group:'+g]);let s=await f.apis[1].snapshot();
 assert.equal(s.messages.length,1);assert.equal(s.messages[0].text,'private text');
 assert(s.groups.find(v=>v.id===g).accepted);assert.deepEqual(s.hiddenChats,['group:'+g]);
 await f.apis[0].enqueueGroup(g,key(),'new group text');await f.deliver(0,1);
 s=await f.apis[1].snapshot();assert.deepEqual(s.hiddenChats,[]);
 assert.equal(s.messages.filter(m=>m.group?.id===g).length,1);
});

test('group replies bind logical message and author across different recipient copies',async()=>{const f=setup(),g=await f.group(),id=key();await f.apis[0].enqueueGroup(g,id,'original');await f.deliver(0,1);await f.deliver(0,2);const reply={id,author:f.accounts[0]};await f.apis[1].enqueueGroup(g,key(),'reply from member',reply);await f.deliver(1,0);await f.deliver(1,2);for(const a of f.apis){const s=await a.snapshot();assert.deepEqual(s.messages.find(m=>m.text==='reply from member').reply,reply);}await assert.rejects(f.apis[2].enqueueGroup(g,key(),'invalid',{id:key(),author:f.accounts[0]}));assert.equal((await f.apis[1].snapshot()).contacts.length,0);});

test('group author edits fan out immutably with separate receipts and permanent deletion',async()=>{const f=setup(),g=await f.group(),id=key(),target={id,author:f.accounts[0]};await f.apis[0].enqueueGroup(g,id,'original');await f.deliver(0,1);await f.deliver(0,2);const edit=key();await f.apis[0].actGroup(g,edit,target,'edit','updated');const packets=chat.pendingRootChat(await f.apis[0].snapshot(),f.accounts[0]);assert.equal(packets.length,2);assert.notEqual(packets[0].id,packets[1].id);await f.apis[0].actGroup(g,edit,target,'edit','updated');assert.equal((await f.apis[0].snapshot()).groupActions.length,2);await f.deliver(0,1);assert.equal((await f.apis[0].snapshot()).groupActions.filter(a=>a.status==='delivered').length,1);await f.deliver(0,2);for(let i=0;i<3;i++){const s=await f.apis[i].snapshot();assert.equal(s.messages[0].text,'original');assert.equal(view(f.accounts[i],s).messages[0].text,'updated');}await assert.rejects(f.apis[1].actGroup(g,key(),target,'delete'));await f.apis[0].actGroup(g,key(),target,'delete');await f.deliver(0,1);await f.deliver(0,2);assert(view(f.accounts[2],await f.apis[2].snapshot()).messages[0].deleted);await assert.rejects(f.apis[0].actGroup(g,key(),target,'edit','resurrect'));});

test('group reactions belong to individual members and removal changes only their choice',async()=>{const f=setup(),g=await f.group(),id=key(),target={id,author:f.accounts[0]};await f.apis[0].enqueueGroup(g,id,'original');await f.deliver(0,1);await f.deliver(0,2);await f.apis[1].actGroup(g,key(),target,'reaction','👍');await f.apis[2].actGroup(g,key(),target,'reaction','❤️');await f.deliver(1,0);await f.deliver(1,2);await f.deliver(2,0);await f.deliver(2,1);assert.equal(view(f.accounts[0],await f.apis[0].snapshot()).messages[0].reactions.length,2);await f.apis[1].actGroup(g,key(),target,'reaction','');await f.deliver(1,0);const choices=view(f.accounts[0],await f.apis[0].snapshot()).messages[0].reactions;assert.deepEqual(choices,[{author:f.accounts[2],text:'❤️'}]);});

test('out-of-order group actions wait for membership and tombstones survive original arriving later',async()=>{const f=setup(),g=key(),id=key(),target={id,author:f.accounts[0]};await f.apis[0].createGroup(g,key(),'Family',f.accounts.slice(1));await f.apis[0].enqueueGroup(g,id,'original');await f.apis[0].actGroup(g,key(),target,'delete');const packets=chat.pendingRootChat(await f.apis[0].snapshot(),f.accounts[0]).filter(p=>p.peer===f.accounts[1]),action=packets.find(p=>JSON.parse(p.raw)[0]==='axonic-root-group-action-v1'),invite=packets.find(p=>JSON.parse(p.raw)[0]==='axonic-group-members-v1'),message=packets.find(p=>JSON.parse(p.raw)[0]==='axonic-root-group-text-v1');assert.equal(await f.apis[1].receive(f.accounts[0],action.id,action.raw),false);assert(await f.apis[1].receive(f.accounts[0],invite.id,invite.raw));assert(await f.apis[1].receive(f.accounts[0],action.id,action.raw));assert(await f.apis[1].receive(f.accounts[0],message.id,message.raw));assert(view(f.accounts[1],await f.apis[1].snapshot()).messages[0].deleted);assert(await f.apis[1].receive(f.accounts[0],action.id,action.raw));assert.equal((await f.apis[1].snapshot()).groupActions.length,1);});

test('forged group actions, cross-group targets, future membership, changed retries and removal fail closed',async()=>{const f=setup(),g=await f.group(),id=key(),target={id,author:f.accounts[0]};await f.apis[0].enqueueGroup(g,id,'original');await f.deliver(0,1);await f.deliver(0,2);const aid=key();await f.apis[0].actGroup(g,aid,target,'edit','updated');await assert.rejects(f.apis[0].actGroup(g,aid,target,'edit','changed'));const p=chat.pendingRootChat(await f.apis[0].snapshot(),f.accounts[0]).find(p=>p.peer===f.accounts[1]),body=JSON.parse(p.raw);assert.equal(await f.apis[1].receive(f.accounts[2],p.id,p.raw),false);body[3].group.revision++;assert.equal(await f.apis[1].receive(f.accounts[0],p.id,JSON.stringify(body)),false);const other=key();await f.apis[0].createGroup(other,key(),'Other',f.accounts.slice(1));await assert.rejects(f.apis[0].actGroup(other,key(),target,'reaction','👍'));await f.apis[0].updateGroup(g,key(),'Family',[f.accounts[2]]);await f.deliver(0,1);assert.equal(await f.apis[1].receive(f.accounts[0],p.id,p.raw),false);await assert.rejects(f.apis[1].actGroup(g,key(),target,'reaction','👍'));});
test('group delivery IDs bind recipient and packet domain for the existing custody store',()=>{const id=key(),a='axonic:1:'+'a'.repeat(64),b='axonic:1:'+'b'.repeat(64);assert.equal(groups.rootGroupDeliveryId(id,a),groups.rootGroupDeliveryId(id,a));assert.notEqual(groups.rootGroupDeliveryId(id,a),groups.rootGroupDeliveryId(id,b));assert.notEqual(groups.rootGroupDeliveryId(id,a),groups.rootGroupDeliveryId(id,a,'axonic-group-members-v1'));});
test('malformed membership, too many members, future versions and forged creator updates fail closed',async()=>{const f=setup(),g=await f.group(),s=await f.apis[0].snapshot(),body={...s.groups[0]};delete body.accepted;delete body.blocked;const id=key(),wire=(from,value)=>JSON.stringify(['axonic-group-members-v1',f.accounts[1],id,value]);assert.equal(await f.apis[1].receive(f.accounts[2],id,wire(f.accounts[2],body)),false);assert.equal(await f.apis[1].receive(f.accounts[0],id,wire(f.accounts[0],{...body,members:[...body.members,body.members[0]]})),false);await assert.rejects(f.apis[0].updateGroup(g,key(),'x','a'.repeat(11).split('').map((_,i)=>'axonic:1:'+i.toString(16).repeat(64))));await f.apis[0].enqueueGroup(g,key(),'current');const p=chat.pendingRootChat(await f.apis[0].snapshot(),f.accounts[0]).find(p=>p.peer===f.accounts[1]),future=JSON.parse(p.raw);future[3].group.revision++;assert.equal(await f.apis[1].receive(f.accounts[0],p.id,JSON.stringify(future)),false);assert.deepEqual((await f.apis[1].snapshot()).groups[0].members,body.members);});
function setup(){const f=fixture(),accounts=f.ids.map(i=>i.record.account),raws=[null,null,null],apis=accounts.map((owner,i)=>chat.createRootChatLedger({owner,current:()=>true,now:()=>now,read:async()=>raws[i],write:async raw=>{raws[i]=raw;},verifyAttachment:async descriptor=>protocol.verifyAttachmentManifest(descriptor.manifest,f.ids[0].record,now),verifyAttachmentReceipt:async(descriptor,receipt)=>protocol.verifyAttachmentReceipt(receipt,descriptor.manifest,f.ids[1].record,now)}));return {...f,accounts,apis,raws,async deliver(i,j){for(const p of chat.pendingRootChat(await apis[i].snapshot(),accounts[i]).filter(p=>p.peer===accounts[j])){assert(await apis[j].receive(accounts[i],p.id,p.raw));await apis[i].delivered(p.peer,p.id);}},async group(){const id=key();await apis[0].createGroup(id,key(),'Family',accounts.slice(1));await this.deliver(0,1);await this.deliver(0,2);for(const a of apis)await a.configureGroup(id,{accepted:true});return id;}};}
test('group invitations and fan-out persist per-recipient receipts and do not become direct chats',async()=>{const f=setup(),g=await f.group(),id=key();await f.apis[0].enqueueGroup(g,id,'hello family');await f.deliver(0,1);let s=await f.apis[0].snapshot();assert.equal(groups.rootGroupMessages(s,g)[0].status,'pending');await f.deliver(0,2);s=await f.apis[0].snapshot();assert.equal(groups.rootGroupMessages(s,g).length,1);assert.equal(groups.rootGroupMessages(s,g)[0].status,'delivered');assert.equal(s.contacts.length,0);for(const a of f.apis)assert.equal(groups.rootGroupMessages(await a.snapshot(),g)[0].text,'hello family');});
test('out-of-order group text waits for membership and duplicates cannot change context or text',async()=>{const f=setup(),g=key(),id=key();await f.apis[0].createGroup(g,key(),'Family',f.accounts.slice(1));await f.apis[0].enqueueGroup(g,id,'queued');const p=chat.pendingRootChat(await f.apis[0].snapshot(),f.accounts[0]).find(p=>p.id===groups.rootGroupDeliveryId(id,f.accounts[1])&&p.peer===f.accounts[1]);assert.equal(await f.apis[1].receive(f.accounts[0],p.id,p.raw),false);const invite=chat.pendingRootChat(await f.apis[0].snapshot(),f.accounts[0]).find(p=>p.peer===f.accounts[1]&&p.id!==groups.rootGroupDeliveryId(id,f.accounts[1]));assert(await f.apis[1].receive(f.accounts[0],invite.id,invite.raw));assert(await f.apis[1].receive(f.accounts[0],p.id,p.raw));assert(await f.apis[1].receive(f.accounts[0],p.id,p.raw));const changed=JSON.parse(p.raw);changed[3].text='forged';assert.equal(await f.apis[1].receive(f.accounts[0],p.id,JSON.stringify(changed)),false);assert.equal((await f.apis[1].snapshot()).messages.length,1);});
test('only the authenticated creator changes membership; removal prevents future group fan-out',async()=>{const f=setup(),g=await f.group();await assert.rejects(f.apis[1].updateGroup(g,key(),'Hijack',f.accounts));const id=key();await f.apis[0].enqueueGroup(g,id,'before removal');await f.apis[0].updateGroup(g,key(),'Family',[f.accounts[1]]);assert(!chat.pendingRootChat(await f.apis[0].snapshot(),f.accounts[0]).some(p=>p.id===groups.rootGroupDeliveryId(id,f.accounts[2])&&p.peer===f.accounts[2]));await f.deliver(0,1);await f.deliver(0,2);await assert.rejects(f.apis[2].enqueueGroup(g,key(),'removed member'));await f.apis[1].enqueueGroup(g,key(),'remaining member');const p=chat.pendingRootChat(await f.apis[1].snapshot(),f.accounts[1])[0];assert(await f.apis[0].receive(f.accounts[1],p.id,p.raw));assert(!chat.pendingRootChat(await f.apis[1].snapshot(),f.accounts[1]).some(p=>p.peer===f.accounts[2]));});
test('leave retries cannot remove a subsequently re-added member',async()=>{const f=setup(),g=await f.group(),id=key();await f.apis[1].leaveGroup(g,id);const p=chat.pendingRootChat(await f.apis[1].snapshot(),f.accounts[1])[0];assert(await f.apis[0].receive(f.accounts[1],p.id,p.raw));await f.apis[0].updateGroup(g,key(),'Family',f.accounts.slice(1));assert(await f.apis[0].receive(f.accounts[1],p.id,p.raw));assert((await f.apis[0].snapshot()).groups[0].members.includes(f.accounts[1]));});
test('group media keeps the signed recipient-specific manifest and waits for its completion receipt',async()=>{const f=setup(),g=await f.group(),descriptor={manifest:f.manifest,key:Buffer.from(f.key).toString('hex'),checksum:crypto.createHash('sha256').update(f.plain).digest('hex'),name:'sample.bin',mime:'application/octet-stream'},context={id:g,revision:1,messageId:key()};await f.apis[0].enqueueAttachment(descriptor,undefined,context);const p=chat.pendingRootChat(await f.apis[0].snapshot(),f.accounts[0]).find(p=>p.id===f.manifest.id);assert(await f.apis[1].receive(f.accounts[0],p.id,p.raw));assert.equal(await f.apis[2].receive(f.accounts[0],p.id,p.raw),false);await f.apis[0].delivered(f.accounts[1],p.id);assert.equal((await f.apis[0].snapshot()).messages[0].status,'pending');const receipt=protocol.signAttachmentReceipt(f.manifest,f.ids[1].signingSeed,f.ids[1].record,now);assert(await f.apis[0].attachmentComplete(f.accounts[1],p.id,'outgoing',receipt));assert.equal((await f.apis[0].snapshot()).messages[0].status,'delivered');});
test('blocked groups and senders are local policy, and corrupt group storage is preserved',async()=>{const f=setup(),g=await f.group();await f.apis[1].configureGroup(g,{blocked:true});await f.apis[0].enqueueGroup(g,key(),'blocked');const p=chat.pendingRootChat(await f.apis[0].snapshot(),f.accounts[0])[0];assert.equal(await f.apis[1].receive(f.accounts[0],p.id,p.raw),false);const old=f.raws[0];f.raws[0]=JSON.stringify({...JSON.parse(old),groups:[{id:g}]});await assert.rejects(f.apis[0].snapshot(),/recovery/);assert.notEqual(f.raws[0],old);});

test('invalid local group preferences and null stored group rows preserve existing state',async()=>{const f=setup(),g=await f.group(),before=f.raws[0];for(const patch of [{accepted:'false'},{blocked:1},{unexpected:true},null]){await assert.rejects(f.apis[0].configureGroup(g,patch),/Invalid group preferences/);assert.equal(f.raws[0],before);}for(const bad of [{groups:[null]},{groupPackets:[null]}]){const raw=JSON.stringify({...JSON.parse(before),...bad});f.raws[0]=raw;await assert.rejects(f.apis[0].snapshot(),/recovery/);assert.equal(f.raws[0],raw);}});
