const actionExports={};new Function('exports',require('typescript').transpileModule(require('fs').readFileSync('src/services/identity/rootChatActions.ts','utf8'),{compilerOptions:{module:1,target:9}}).outputText)(actionExports);
const test=require('node:test'),assert=require('node:assert/strict'),fs=require('node:fs'),ts=require('typescript');
function setup(){let unlocked=true,owner='owner',exists=true,lookup='found';const calls=[],message={peer:'source',id:'original',direction:'incoming',text:'hello',status:'delivered'};const contact={account:'target',blocked:false};const source={peer:message.peer,id:message.id,direction:message.direction};const native={identityRandomBytes:async()=> 'fresh-id'};const out={};new Function('require','exports',ts.transpileModule(fs.readFileSync('src/services/identity/rootMessageForward.ts','utf8'),{compilerOptions:{module:1,target:9}}).outputText)(name=>({
 '../../../modules/axonic-nearby':{default:native},'./localAccount':{localAccount:{status:()=>({account:owner,state:unlocked?'unlocked':'locked'})}},'./localRootChat':{localRootChat:()=>({snapshot:async()=>({contacts:[contact],messages:[message]}),enqueue:async(...args)=>calls.push(['text',...args])})},'./localAccountNetwork':{localAccountLookupIdentity:async()=>{throw Error('Forwarding must not require an online lookup');}},'./rootAttachmentRuntime':{queueRootAttachmentSource:async(...args)=>calls.push(['file',...args])},'./rootAttachmentFiles':{rootAttachmentFile:()=>({get exists(){return exists;},uri:'own-file'})},'./attachmentProtocol':{attachmentDigest:()=> 'digest'},'./identityProtocol':{validAccountId:()=>true},'./rootChatActions':actionExports
 }[name]),out);return {out,calls,message,contact,source,native,lock:()=>unlocked=false,switch:()=>owner='other',missing:()=>exists=false,noIdentity:()=>lookup='missing'};}
test('forward text rereads original history and uses a fresh ID',async()=>{const f=setup();await f.out.forwardRootMessage({...f.source,text:'forged'},'target');assert.deepEqual(f.calls,[['text','target','fresh-id','hello']]);});
test('forward attachment stages own bytes with the destination instead of reusing encrypted descriptor',async()=>{const f=setup();f.message.attachment={manifest:{},key:'old-key',name:'photo.png',mime:'image/png'};await f.out.forwardRootMessage(f.source,'target');assert.deepEqual(f.calls,[['file','target','own-file','photo.png','image/png','owner']]);});
test('pending incoming attachment cannot be forwarded',async()=>{const f=setup();f.message.attachment={manifest:{}};f.message.status='pending';await assert.rejects(f.out.forwardRootMessage(f.source,'target'),/downloading/);assert.equal(f.calls.length,0);});
test('missing own attachment bytes cannot enqueue a forward',async()=>{const f=setup();f.message.attachment={manifest:{}};f.missing();await assert.rejects(f.out.forwardRootMessage(f.source,'target'));assert.equal(f.calls.length,0);});
test('attachment forwarding stages bytes while the recipient directory is unavailable',async()=>{const f=setup();f.noIdentity();f.message.attachment={manifest:{},name:'photo.png',mime:'image/png'};await f.out.forwardRootMessage(f.source,'target');assert.deepEqual(f.calls,[['file','target','own-file','photo.png','image/png','owner']]);});
test('blocked recipient and stale source cannot forward',async()=>{const f=setup();f.contact.blocked=true;await assert.rejects(f.out.forwardRootMessage(f.source,'target'),/blocked/);f.contact.blocked=false;await assert.rejects(f.out.forwardRootMessage({...f.source,id:'absent'},'target'),/no longer/);});
test('lock or account switch while allocating ID prevents send',async()=>{for(const mode of ['lock','switch']){const f=setup();f.native.identityRandomBytes=async()=>{f[mode]();return 'fresh';};await assert.rejects(f.out.forwardRootMessage(f.source,'target'),/Unlock/);assert.equal(f.calls.length,0);}});

