const test=require('node:test'),assert=require('node:assert/strict'),fs=require('fs'),ts=require('typescript');
function setup(){const out={};new Function('exports',ts.transpileModule(fs.readFileSync('src/services/identity/rootVoiceRecorder.ts','utf8'),{compilerOptions:{module:1,target:9}}).outputText)(out);const events=[],d={current:()=>true,permission:async()=>true,mode:async r=>events.push(['mode',r]),prepare:async()=>events.push('prepare'),record:()=>events.push('record'),stop:async()=>events.push('stop'),uri:()=> 'file://voice',remove:u=>events.push(['remove',u]),enqueue:async u=>events.push(['send',u]),now:()=>1000,changed:s=>events.push(s)};return {out,d,events,create:()=>out.createRootVoiceRecorder(d)};}
test('voice send stages once, restores audio mode and removes only recorder temporary file',async()=>{const f=setup(),c=f.create();await c.start();assert(f.out.rootVoiceRecordingActive());f.d.now=()=>2500;await Promise.all([c.send(),c.send()]);assert.equal(f.events.filter(e=>Array.isArray(e)&&e[0]==='send').length,1);assert(!f.out.rootVoiceRecordingActive());assert.deepEqual(f.events.slice(-2),[['remove','file://voice'],'idle']);});
test('cancel during permission prompt never starts microphone or sends',async()=>{const f=setup();let resolve;f.d.permission=()=>new Promise(r=>resolve=r);const c=f.create(),starting=c.start();await Promise.resolve();const cancel=c.cancel();resolve(true);await starting;await cancel;assert(!f.events.includes('record'));assert(!f.events.some(e=>Array.isArray(e)&&e[0]==='send'));assert(!f.out.rootVoiceRecordingActive());});
test('lock during recording prevents sending',async()=>{const f=setup(),c=f.create();await c.start();f.d.current=()=>false;f.d.now=()=>3000;await c.send();assert(!f.events.some(e=>Array.isArray(e)&&e[0]==='send'));});
test('unmount during preparation stops and releases recording activity',async()=>{const f=setup();let resolve;f.d.prepare=()=>new Promise(r=>resolve=r);const c=f.create(),start=c.start();while(!resolve)await Promise.resolve();const end=c.dispose();resolve();await start;await end;assert(!f.events.includes('record'));assert(!f.out.rootVoiceRecordingActive());});
test('denied permission and short clips cannot be sent',async()=>{const f=setup(),c=f.create();f.d.permission=async()=>false;await assert.rejects(c.start(),/microphone/);assert(!f.out.rootVoiceRecordingActive());f.d.permission=async()=>true;await c.start();await assert.rejects(c.send(),/half a second/);assert(!f.events.some(e=>Array.isArray(e)&&e[0]==='send'));});

test('failed send releases recorder activity so future recording is possible',async()=>{const f=setup(),c=f.create();await c.start();f.d.now=()=>3000;f.d.enqueue=async()=>{throw Error('Disk full');};await assert.rejects(c.send(),/Disk full/);assert(!f.out.rootVoiceRecordingActive());await c.start();assert(f.events.filter(e=>e==='record').length===2);await c.cancel();});

test('native stop failure still restores audio mode and releases activity',async()=>{const f=setup(),c=f.create();await c.start();f.d.stop=async()=>{throw Error('Recorder stopped');};await assert.rejects(c.send(),/Recorder stopped/);assert(f.events.some(e=>Array.isArray(e)&&e[0]==='mode'&&e[1]===false));assert(!f.out.rootVoiceRecordingActive());});
