const test=require('node:test'),assert=require('node:assert/strict'),fs=require('node:fs'),ts=require('typescript');
test('background recovery drives delivery without relying on display-frame JS timers',async()=>{const f=fixture({nativeClock:true});await f.out.recoverRootMessage('own','peer','id',160000);assert.equal(f.counts().jsTimers,0);assert.ok(f.counts().ticks>1);assert.ok(f.counts().elapsed>=20000);assert.deepEqual(f.leases,[30000,0]);});
test('a durable inbox entry does not close the wake transport before the receipt exchange',async()=>{const f=fixture();await f.out.recoverRootMessage('own','peer','id',160000);assert.equal(f.counts().resumed,1);assert.ok(f.counts().elapsed>=20000);assert.ok(f.counts().elapsed<30000);assert.equal(f.counts().stopped,1);});
function fixture({state='unlocked',resume=false,native=true,fail=false,nativeClock=false}={}){
 let now=100000,started=0,resumed=0,stopped=0,owner='own',inspects=0,initializes=0,ticks=0,jsTimers=0;const leases=[];
 const imports={'react-native':{AppState:{currentState:'background'}},'../../../modules/axonic-nearby':{default:native?{axonMessageWake:ms=>leases.push(ms),...(nativeClock?{axonMessageWait:async ms=>{now+=ms;}}:{})}:{}},'./localAccount':{localAccount:{status:()=>({state,account:owner}),inspect:async()=>{inspects++;}},localAccountSession:{initialize:async()=>{initializes++;if(resume)state='unlocked';}}},'./localAccountNetwork':{startLocalAccountNetwork:()=>{started++;return {resume:()=>resumed++,tick:()=>{ticks++;if(fail)throw Error('pump');},stop:()=>stopped++};}},'./localRootChat':{localRootChat:()=>({snapshot:async()=>{if(fail)throw Error('storage');return {messages:[{peer:'peer',id:'id',direction:'incoming'}]};}})}};
 const out={};new Function('exports','require','Date','setTimeout',ts.transpileModule(fs.readFileSync('src/services/identity/rootMessageRecovery.ts','utf8'),{compilerOptions:{module:1,target:9}}).outputText)(out,n=>imports[n],{now:()=>now},(cb,ms)=>{jsTimers++;now+=ms;queueMicrotask(cb);});
 return {out,leases,counts:()=>({started,resumed,stopped,initializes,inspects,ticks,jsTimers,elapsed:now-100000}),change:()=>owner='other'};
}
test('unlocked verified-wake recovery acquires a bounded native window and releases its transport lease',async()=>{const f=fixture();await f.out.recoverRootMessage('own','peer','id',160000);assert.deepEqual(f.leases,[30000,0]);assert.equal(f.counts().started,1);assert.equal(f.counts().stopped,1);});
test('locked or mismatched accounts and old native builds cannot access background transport',async()=>{for(const options of [{state:'locked'},{native:false}]){const f=fixture(options);await f.out.recoverRootMessage('own','peer','id',160000);assert.equal(f.counts().started,0);assert.deepEqual(f.leases,[]);}const f=fixture();f.change();await f.out.recoverRootMessage('own','peer','id',160000);assert.equal(f.counts().started,0);});
test('remembered session may resume; storage failure still releases native and runtime leases',async()=>{const resumed=fixture({state:'locked',resume:true});await resumed.out.recoverRootMessage('own','peer','id',160000);assert.equal(resumed.counts().initializes,1);assert.equal(resumed.counts().started,1);const f=fixture({fail:true});await assert.rejects(f.out.recoverRootMessage('own','peer','id',160000));assert.deepEqual(f.leases,[30000,0]);assert.equal(f.counts().stopped,1);});
