const test=require('node:test'),assert=require('node:assert/strict'),fs=require('node:fs'),ts=require('typescript');
const out={};new Function('exports',ts.transpileModule(fs.readFileSync('src/services/sticker-draft-store.ts','utf8'),{compilerOptions:{module:1,target:9}}).outputText)(out);
function setup(){let saved=null,seq=0,allowed=true,fail=false;const files=new Set();const d={read:async()=>saved,write:async value=>{if(fail)throw Error('disk full');saved=value;},stage:uri=>{const id=String(++seq);files.add(id);return {id,uri:'own/'+id};},remove:v=>files.delete(v.id),current:()=>allowed};return {store:out.createStickerDraftStore(d),restart:()=>out.createStickerDraftStore(d),files,deny:()=>allowed=false,fail:()=>fail=true};}
test('draft image and name survive editor recreation',async()=>{const f=setup(),draft=await f.store.replace('photo');await f.store.rename(draft.id,'My sticker');assert.deepEqual(await f.restart().load(),{...draft,name:'My sticker'});});
test('failed replacement keeps previous draft and removes only new staged copy',async()=>{const f=setup(),old=await f.store.replace('photo');f.fail();await assert.rejects(f.store.replace('edited'),/disk full/);assert.deepEqual(await f.store.load(),old);assert.deepEqual([...f.files],[old.id]);});
test('old editor cannot delete or rename a newer draft',async()=>{const f=setup(),a=await f.store.replace('one'),b=await f.store.replace('two');await f.store.clear(a.id);await f.store.rename(a.id,'stale');assert.deepEqual(await f.store.load(),b);assert(!f.files.has(a.id));});
test('cancel deletes only the owned draft after the index commits',async()=>{const f=setup(),a=await f.store.replace('photo');await f.store.clear(a.id);assert.equal(await f.store.load(),null);assert.equal(f.files.size,0);});
test('account switch during staged selection does not write or retain new file',async()=>{const f=setup(),pending=f.store.replace('photo');f.deny();await assert.rejects(pending,/Account changed/);assert.equal(f.files.size,0);await assert.rejects(f.store.load(),/Account changed/);});
test('failed cancel preserves draft and its file',async()=>{const f=setup(),draft=await f.store.replace('photo');f.fail();await assert.rejects(f.store.clear(draft.id),/disk full/);assert(f.files.has(draft.id));assert.deepEqual(await f.store.load(),draft);});
