import {StyleSheet} from 'react-native';
import {Font,Spacing,Radius} from '../../theme';
export const groupInfoStyles = StyleSheet.create({
  container: { flex: 1 }, center: { flex: 1, alignItems: 'center', justifyContent: 'center' }, list: { paddingBottom: Spacing.lg },
  hero: { alignItems: 'center', padding: Spacing.lg, margin: Spacing.md, borderWidth: 1, borderRadius: Radius.lg }, photoWrap: { position: 'relative', marginBottom: Spacing.sm }, cameraBadge: { position: 'absolute', right: -2, bottom: -2, width: 27, height: 27, borderRadius: 14, alignItems: 'center', justifyContent: 'center' }, nameRow: { flexDirection: 'row', alignItems: 'center', gap: Spacing.sm, maxWidth: '100%' }, name: { fontSize: Font.size.lg, ...Font.semiBold, maxWidth: '85%' }, count: { fontSize: Font.size.sm, marginTop: 4 }, created: { fontSize: Font.size.xs, marginTop: 3 },
  divider: { width: '100%', height: StyleSheet.hairlineWidth, marginVertical: Spacing.lg }, heroActions: { flexDirection: 'row', justifyContent: 'center', gap: Spacing.xl }, heroAction: { alignItems: 'center', gap: Spacing.xs, minWidth: 74 }, heroActionIcon: { width: 50, height: 50, borderRadius: 25, borderWidth: 1, alignItems: 'center', justifyContent: 'center' }, heroActionText: { fontSize: Font.size.sm, ...Font.medium },
  action: { marginHorizontal: Spacing.md, minHeight: 48, paddingHorizontal: Spacing.md, borderWidth: 1, borderRadius: Radius.md, flexDirection: 'row', alignItems: 'center', gap: Spacing.sm }, actionText: { fontSize: Font.size.md, ...Font.medium }, section: { fontSize: Font.size.xs, fontWeight: '700', letterSpacing: 1, marginHorizontal: Spacing.md, marginTop: Spacing.lg, marginBottom: Spacing.xs },
  member: { flexDirection: 'row', alignItems: 'center', paddingHorizontal: Spacing.md, paddingVertical: Spacing.sm, borderBottomWidth: StyleSheet.hairlineWidth }, memberInfo: { flex: 1, marginLeft: Spacing.md }, memberName: { fontSize: Font.size.md, ...Font.medium }, memberSub: { fontSize: Font.size.sm, marginTop: 2 }, admin: { fontSize: 10, fontWeight: '700', letterSpacing: .6, borderWidth: 1, paddingHorizontal: 6, paddingVertical: 3, borderRadius: Radius.sm }, remove: { padding: Spacing.sm, marginLeft: Spacing.xs },
  footer: { padding: Spacing.md, marginTop: Spacing.lg }, leave: { minHeight: 45, borderWidth: 1, borderRadius: Radius.md, alignItems: 'center', justifyContent: 'center', flexDirection: 'row', gap: Spacing.sm }, leaveText: { fontSize: Font.size.md, ...Font.semiBold },
  modalShade: { flex: 1, backgroundColor: 'rgba(0,0,0,.55)', justifyContent: 'center', padding: Spacing.lg }, modal: { borderRadius: Radius.lg, padding: Spacing.lg }, modalTitle: { fontSize: Font.size.lg, ...Font.semiBold }, input: { marginTop: Spacing.md, borderWidth: 1, borderRadius: Radius.md, minHeight: 48, paddingHorizontal: Spacing.md, fontSize: Font.size.md }, modalActions: { flexDirection: 'row', justifyContent: 'flex-end', gap: Spacing.lg, marginTop: Spacing.lg },
  picker: { flex: 1 }, pickerHeader: { padding: Spacing.md, flexDirection: 'row', alignItems: 'center', justifyContent: 'space-between', borderBottomWidth: StyleSheet.hairlineWidth }, contact: { minHeight: 66, paddingHorizontal: Spacing.md, flexDirection: 'row', alignItems: 'center', borderBottomWidth: StyleSheet.hairlineWidth }, empty: { textAlign: 'center', marginTop: Spacing.xl, paddingHorizontal: Spacing.lg },
});
