import {rootMessageStatus,deliveryStatusIcon,deliveryStatusLabel} from '../../modules/messaging';
import {pickRootGroupAttachment} from '../../modules/ui/documentPicker';
import ReplySwipe from '../../components/chat/ReplySwipe';
import {ThemedAlert as Alert} from '../../components/ui/ThemedAlert';
import Avatar from '../../components/ui/Avatar';
import Input from '../../components/ui/Input';
import SmartMessageText from '../../components/SmartMessageText';
import ChatHeaderIdentity from '../../components/chat/ChatHeaderIdentity';
import {groupCreateStyles as createStyles} from './group-create-styles';
import {groupInfoStyles as infoStyles} from './group-info-styles';
import {shortIdentity,parseIdentityCode} from '../../modules/identity';
import * as Clipboard from 'expo-clipboard';
import RootMessageMenu from '../../components/chat/RootMessageMenu';
import {rootChatView} from '../../modules/messaging';
import type {RootChatMessage,RootChatReply} from '../../modules/messaging';
import React,{useEffect,useLayoutEffect,useState} from 'react';
import {AppState,FlatList,KeyboardAvoidingView,Platform,Pressable,ScrollView,Text,TextInput,TouchableOpacity,View} from 'react-native';
import type {NativeStackScreenProps} from '@react-navigation/native-stack';
import {useIsFocused} from '@react-navigation/native';
import {useHeaderHeight} from '@react-navigation/elements';
import {useSafeAreaInsets} from 'react-native-safe-area-context';
import {Ionicons} from '@expo/vector-icons';
import {useTheme} from '../../contexts/ThemeContext';
import {messaging} from '../../modules/messaging';
import {localAccount} from '../../modules/identity';
import {conversations} from '../../modules/messaging';
import {rootGroupMessages} from '../../modules/messaging';
import type {RootChatState} from '../../modules/messaging';
import type {RootAccountRoutes} from '../../navigation/rootAccountRoutes';
import {chatRoomStyles as styles} from '../../components/chat/chat-room-styles';
import {messageBubbleStyles as bubbles} from '../../components/chat/message-bubble-styles';
import RootAttachmentBubble from '../../components/RootAttachmentBubble';
import RootVoiceComposer from '../../components/chat/RootVoiceComposer';
import AttachmentMenu from '../../components/chat/AttachmentMenu';
import StickerPicker from '../../components/chat/sticker-picker';
import StickerArt from '../../components/chat/sticker-art';
import {parseSticker,stickerMessage} from '../../services/stickers';
import {rootStickerDraft} from '../../modules/messaging';
import {importedStickerUri,stickerFileMime} from '../../services/imported-stickers';
import {IMPORTED_STICKER_CONTENT} from '../../services/sticker-file-format';
import {attachmentDigest} from '../../modules/messaging';
import {rootGroupAttachmentAudience,queueRootGroupAttachmentSource,rootAttachmentProgress,retryRootAttachmentSelection,removeRootAttachmentSelection} from '../../modules/messaging';
import {pickRootGroupMedia} from '../../modules/ui/mediaPicker';
type Screen<P extends keyof RootAccountRoutes>=NativeStackScreenProps<RootAccountRoutes,P>;
const report=(e:unknown)=>Alert.alert('Axonic',e instanceof Error?e.message:'Please try again');
function useGroups(){const [state,set]=useState<RootChatState>({version:1,messages:[],contacts:[]});useEffect(()=>{let active=true,busy=false,lastError='';const refresh=async()=>{if(busy)return;busy=true;try{const s=await conversations().snapshot();if(active){set(rootChatView(localAccount.status().account!,s));lastError='';}}catch(e){const message=e instanceof Error?e.message:'Could not read group chats';if(active&&localAccount.status().state==='unlocked'&&message!==lastError){lastError=message;report(e);}}finally{busy=false;}};void refresh();const t=setInterval(()=>void refresh(),700);return()=>{active=false;clearInterval(t);};},[]);return state;}
export function RootGroupCreate({navigation}:Screen<'GroupCreate'>){
 const {colors}=useTheme(),state=useGroups(),[name,setName]=useState(''),[code,setCode]=useState(''),[members,setMembers]=useState<string[]>([]),[busy,setBusy]=useState(false);
 const insets=useSafeAreaInsets(),owner=localAccount.status().account,add=(peer:string)=>{if(peer===owner){report(Error('You are already in the group'));return;}setMembers(old=>old.includes(peer)?old.filter(p=>p!==peer):old.length<9?[...old,peer]:old);};
 async function create(){if(busy||!name.trim()||!members.length)return;setBusy(true);try{const id=await messaging.createGroup(name,members);navigation.replace('GroupRoom',{id});}catch(e){report(e);}finally{setBusy(false);}}
 const rows=[...state.contacts.filter(c=>!c.blocked),...members.filter(p=>!state.contacts.some(c=>c.account===p)).map(account=>({account,alias:'',blocked:false,accepted:true}))];
 return <View style={[createStyles.container,{backgroundColor:colors.background}]}><View style={createStyles.form}><Input accessibilityLabel="Group name" placeholder="Group name" value={name} onChangeText={setName} maxLength={80}/><Text style={[createStyles.helper,{color:colors.textSecondary}]}>{members.length}/9 members selected</Text><View style={{flexDirection:'row',alignItems:'center',gap:8}}><View style={{flex:1}}><Input accessibilityLabel="Group member identity" placeholder="Paste an axon code…" autoCapitalize="none" autoCorrect={false} value={code} onChangeText={setCode}/></View><TouchableOpacity accessibilityLabel="Add identity" disabled={busy} onPress={()=>{const account=parseIdentityCode(code);if(!account){report(Error('Enter a complete Axonic identity'));return;}add(account);setCode('');}}><Ionicons name="add-circle-outline" size={28} color={colors.primary}/></TouchableOpacity></View></View>
  <FlatList data={rows} keyExtractor={c=>c.account} contentContainerStyle={rows.length?[createStyles.list,{paddingBottom:88+insets.bottom}]:createStyles.empty} ListEmptyComponent={<View style={createStyles.empty}><Ionicons name="people-outline" size={42} color={colors.textTertiary}/><Text style={[createStyles.emptyText,{color:colors.textSecondary}]}>Choose a contact or paste an identity above.</Text></View>} renderItem={({item:c})=><TouchableOpacity disabled={busy} style={[createStyles.contact,{borderBottomColor:colors.divider}]} onPress={()=>add(c.account)}><Avatar name={c.alias||shortIdentity(c.account)} size={46}/><View style={createStyles.contactInfo}><Text numberOfLines={1} style={[createStyles.contactName,{color:colors.text}]}>{c.alias||shortIdentity(c.account)}</Text><Text style={[createStyles.contactSub,{color:colors.textSecondary}]}>{shortIdentity(c.account)}</Text></View><Ionicons name={members.includes(c.account)?'checkmark-circle':'ellipse-outline'} size={26} color={members.includes(c.account)?colors.primary:colors.textTertiary}/></TouchableOpacity>}/>
  <View style={[createStyles.footer,{backgroundColor:colors.background,borderTopColor:colors.divider,paddingBottom:16+insets.bottom}]}><TouchableOpacity accessibilityLabel="Create group" disabled={busy||!name.trim()||!members.length} onPress={()=>void create()} style={[createStyles.createButton,{backgroundColor:busy||!name.trim()||!members.length?colors.surfaceVariant:colors.primary}]}><Ionicons name="people" size={19} color="#fff"/><Text style={createStyles.createText}>{busy?'Creating…':'Create group'}</Text></TouchableOpacity></View>
 </View>;
}
export function RootGroupInfo({route,navigation}:Screen<'GroupInfo'>){
 const {colors}=useTheme(),state=useGroups(),g=state.groups?.find(g=>g.id===route.params.id),owner=localAccount.status().account,[name,setName]=useState(''),[member,setMember]=useState(''),[renaming,setRenaming]=useState(false),[adding,setAdding]=useState(false),[busy,setBusy]=useState(false);
 useEffect(()=>{setName(g?.name??'');},[g?.name]);
 async function update(members:string[]){if(!g||busy)return;setBusy(true);try{await messaging.updateGroup(g.id,name,members);setAdding(false);setRenaming(false);setMember('');}catch(e){report(e);}finally{setBusy(false);}}
 if(!g)return <Text style={{color:colors.text,padding:24}}>Group unavailable</Text>;
 return <ScrollView style={{backgroundColor:colors.background}} contentContainerStyle={infoStyles.list}>
  <View style={[infoStyles.hero,{backgroundColor:colors.surface,borderColor:colors.neonBorder}]}><View style={infoStyles.photoWrap}><Avatar name={g.name} size={82}/></View><View style={infoStyles.nameRow}><Text numberOfLines={1} style={[infoStyles.name,{color:colors.text}]}>{g.name}</Text>{g.admin===owner&&<TouchableOpacity accessibilityLabel="Rename group" onPress={()=>setRenaming(!renaming)}><Ionicons name="pencil" size={19} color={colors.primary}/></TouchableOpacity>}</View><Text style={[infoStyles.count,{color:colors.textSecondary}]}>{g.members.length} members</Text><View style={[infoStyles.divider,{backgroundColor:colors.divider}]}/><TouchableOpacity style={infoStyles.heroAction} onPress={()=>navigation.navigate('GroupRoom',{id:g.id})}><View style={[infoStyles.heroActionIcon,{backgroundColor:colors.highlight,borderColor:colors.neonBorder}]}><Ionicons name="chatbubble-ellipses-outline" size={22} color={colors.primary}/></View><Text style={[infoStyles.heroActionText,{color:colors.text}]}>Message</Text></TouchableOpacity></View>
  {renaming&&g.admin===owner&&<View style={{padding:16}}><Input accessibilityLabel="Group name" value={name} onChangeText={setName} maxLength={80}/><TouchableOpacity disabled={busy||!name.trim()} onPress={()=>void update(g.members)}><Text style={{color:colors.primary}}>Save group name</Text></TouchableOpacity></View>}
  {g.admin===owner&&<TouchableOpacity style={[infoStyles.action,{backgroundColor:colors.surface,borderColor:colors.neonBorder}]} onPress={()=>setAdding(!adding)}><Ionicons name="person-add-outline" size={20} color={colors.primary}/><Text style={[infoStyles.actionText,{color:colors.text}]}>Add members</Text></TouchableOpacity>}
  {adding&&g.admin===owner&&<View style={{padding:16}}><Input accessibilityLabel="New group member identity" value={member} onChangeText={setMember} placeholder="Paste an axon code…" autoCapitalize="none" autoCorrect={false}/><TouchableOpacity disabled={busy} onPress={()=>{const account=parseIdentityCode(member);if(!account){report(Error('Enter a complete Axonic identity'));return;}void update([...new Set([...g.members,account])]);}}><Text style={{color:colors.primary}}>Add identity</Text></TouchableOpacity>{state.contacts.filter(c=>!c.blocked&&!g.members.includes(c.account)).map(c=><TouchableOpacity key={c.account} disabled={busy} style={infoStyles.contact} onPress={()=>void update([...g.members,c.account])}><Avatar name={c.alias||shortIdentity(c.account)} size={44}/><View style={infoStyles.memberInfo}><Text style={[infoStyles.memberName,{color:colors.text}]}>{c.alias||shortIdentity(c.account)}</Text></View><Ionicons name="add-circle-outline" size={26} color={colors.primary}/></TouchableOpacity>)}</View>}
  <Text style={[infoStyles.section,{color:colors.textSecondary}]}>MEMBERS</Text>{g.members.map(p=><View key={p} style={[infoStyles.member,{borderBottomColor:colors.divider}]}><Avatar name={p===owner?'You':state.contacts.find(c=>c.account===p)?.alias||shortIdentity(p)} size={44}/><View style={infoStyles.memberInfo}><Text style={[infoStyles.memberName,{color:colors.text}]}>{p===owner?'You':state.contacts.find(c=>c.account===p)?.alias||shortIdentity(p)}</Text><Text style={[infoStyles.memberSub,{color:colors.textSecondary}]}>{shortIdentity(p)}</Text></View>{p===g.admin&&<Text style={[infoStyles.admin,{color:colors.primary,borderColor:colors.primary}]}>ADMIN</Text>}{g.admin===owner&&p!==owner&&<TouchableOpacity accessibilityLabel="Remove member" disabled={busy} style={infoStyles.remove} onPress={()=>Alert.alert('Remove member?','This changes the group membership for everyone.',[{text:'Cancel',style:'cancel'},{text:'Remove',style:'destructive',onPress:()=>void update(g.members.filter(m=>m!==p))}])}><Ionicons name="person-remove-outline" size={20} color={colors.error}/></TouchableOpacity>}</View>)}
  <View style={infoStyles.footer}><TouchableOpacity style={[infoStyles.leave,{borderColor:colors.error}]} onPress={()=>void conversations().configureGroup(g.id,{blocked:!g.blocked}).catch(report)}><Ionicons name="ban-outline" size={19} color={colors.error}/><Text style={[infoStyles.leaveText,{color:colors.error}]}>{g.blocked?'Unblock group':'Block group'}</Text></TouchableOpacity><TouchableOpacity disabled={busy} style={[infoStyles.leave,{borderColor:colors.error,marginTop:16}]} onPress={()=>Alert.alert(g.admin===owner?'Close group?':'Leave group?',g.admin===owner?'All other members will be removed.':'A leave request will be delivered to the creator.',[{text:'Cancel',style:'cancel'},{text:'Confirm',style:'destructive',onPress:()=>void messaging.leaveGroup(g.id).then(()=>navigation.goBack()).catch(report)}])}><Ionicons name="exit-outline" size={19} color={colors.error}/><Text style={[infoStyles.leaveText,{color:colors.error}]}>{g.admin===owner?'Close group':'Leave group'}</Text></TouchableOpacity></View>
 </ScrollView>;
}
export function RootGroupRoom({route,navigation}:Screen<'GroupRoom'>){const {colors}=useTheme(),state=useGroups(),g=state.groups?.find(g=>g.id===route.params.id),owner=localAccount.status().account,header=useHeaderHeight(),insets=useSafeAreaInsets(),[text,setText]=useState(''),[reply,setReply]=useState<RootChatReply>(),[editing,setEditing]=useState<RootChatMessage>(),[menu,setMenu]=useState<RootChatMessage>(),[busy,setBusy]=useState(false),[attach,setAttach]=useState(false),[stickers,setStickers]=useState(false),[voice,setVoice]=useState(false),[transfers,setTransfers]=useState<Awaited<ReturnType<typeof rootAttachmentProgress>>>({jobs:[],selections:[]});
 const focused=useIsFocused(),[foreground,setForeground]=useState(AppState.currentState==='active'),unread=state.messages.filter(m=>m.group?.id===route.params.id&&m.direction==='incoming'&&!m.read).length;
 useEffect(()=>{const listener=AppState.addEventListener('change',state=>setForeground(state==='active'));return()=>listener.remove();},[]);
 useEffect(()=>{if(focused&&foreground&&g?.accepted&&!g.blocked&&unread)void conversations().markGroupRead(route.params.id).catch(report);},[focused,foreground,g?.accepted,g?.blocked,unread,route.params.id]);
 useEffect(()=>{let active=true;const t=setInterval(()=>void rootAttachmentProgress().then(v=>{if(active)setTransfers(v);}).catch(()=>{}),700);return()=>{active=false;clearInterval(t);};},[]);
 useLayoutEffect(()=>navigation.setOptions({headerTitleAlign:'left',headerBackButtonDisplayMode:'minimal',headerTitle:()=> <ChatHeaderIdentity title={g?.name??'Group'} syncing={false} avatarUri={null} isGroup isOnline={false} color={colors.headerText} onPress={()=>navigation.navigate('GroupInfo',{id:route.params.id})}/>}),[navigation,g?.name,route.params.id,colors.headerText]);
 const disabled=busy||!g||g.blocked||!g.accepted||!g.members.includes(owner!);
 async function work(fn:()=>Promise<unknown>){if(busy)return;setBusy(true);try{await fn();}catch(e){report(e);}finally{setBusy(false);}}
 const target=(m:RootChatMessage):RootChatReply=>({id:m.group!.messageId,author:m.direction==='outgoing'?owner!:m.peer});
 const act=(m:RootChatMessage,kind:'edit'|'delete'|'reaction',value='')=>work(async()=>{await messaging.actGroup(route.params.id,target(m),kind,value,owner);});
 const send=(value:string)=>work(async()=>{if(editing)await messaging.actGroup(route.params.id,target(editing),'edit',value,owner);else await messaging.sendGroupText(route.params.id,value,reply,owner);setText('');setReply(undefined);setEditing(undefined);});
 const messages=rootGroupMessages(state,route.params.id).reverse();
 return <KeyboardAvoidingView style={{flex:1,backgroundColor:colors.chatBg}} behavior={Platform.OS==='ios'?'padding':'height'} keyboardVerticalOffset={header}>
  {g&&!g.accepted&&!g.blocked&&<View style={[styles.requestBanner,{backgroundColor:colors.surface}]}><Text style={{color:colors.text,flex:1}}>Group invitation</Text><Pressable accessibilityLabel="Accept group" onPress={()=>void conversations().configureGroup(g.id,{accepted:true}).catch(report)}><Text style={{color:colors.primary}}>Accept</Text></Pressable></View>}
  {g?.blocked&&<Text style={{color:colors.error,padding:12}}>This group is blocked.</Text>}{g&&!g.members.includes(owner!)&&<Text style={{color:colors.textSecondary,padding:12}}>You are no longer a member.</Text>}
  <FlatList inverted data={messages} keyExtractor={m=>(m.direction==='outgoing'?'own':m.peer)+':'+m.group!.messageId} style={styles.messageList} contentContainerStyle={styles.messagesList} renderItem={({item:m})=>{const mine=m.direction==='outgoing',sticker=parseSticker(m.text);return <ReplySwipe disabled={disabled||m.deleted} onReply={()=>{setEditing(undefined);setReply(target(m));}}><View style={[bubbles.bubbleRow,mine?bubbles.bubbleRowRight:bubbles.bubbleRowLeft]}><Pressable onLongPress={()=>{if(!disabled&&!m.deleted)setMenu(m);}} style={[bubbles.bubble,mine?bubbles.bubbleSent:bubbles.bubbleReceived,{backgroundColor:mine?colors.bubbleSent:colors.bubbleReceived,borderColor:colors.neonBorder,minWidth:m.attachment?260:96},!m.deleted&&(sticker||m.attachment?.name===IMPORTED_STICKER_CONTENT)&&bubbles.stickerBubble]}>{!mine&&<Text style={{color:colors.primary,fontSize:12}}>{state.contacts.find(c=>c.account===m.peer)?.alias||shortIdentity(m.peer)}</Text>}{m.reply&&<Text style={{color:colors.textSecondary,fontSize:12,paddingBottom:8}}>↳ {messages.find(q=>q.group?.messageId===m.reply!.id&&(q.direction==='outgoing'?owner:q.peer)===m.reply!.author)?.text??'Original message unavailable'}</Text>}{m.attachment&&!m.deleted?<RootAttachmentBubble message={m} progress={transfers.jobs.find(j=>j.digest===attachmentDigest(m.attachment!.manifest))} onError={report}/>:sticker&&!m.deleted?<StickerArt sticker={sticker} size={150}/>:m.deleted?<Text style={[bubbles.deletedText,{color:colors.textSecondary}]}>Message deleted</Text>:<SmartMessageText style={[bubbles.messageText,{color:colors.text}]} linkColor={colors.primary}>{m.text}</SmartMessageText>}{!!m.reactions?.length&&<Text style={{color:colors.primary,paddingTop:6}}>{m.reactions.map(r=>r.text).join(' ')}</Text>}<View style={bubbles.metaRow}><Text style={{color:colors.textTertiary,fontSize:11}}>{new Date(m.at).toLocaleTimeString([],{hour:'2-digit',minute:'2-digit'})}{m.edited?' · edited':''}</Text>{mine&&<Ionicons accessibilityLabel={deliveryStatusLabel(rootMessageStatus(m))} name={deliveryStatusIcon(rootMessageStatus(m))} size={13} color={rootMessageStatus(m)==='read'?colors.checkBlue:colors.textTertiary}/>}</View></Pressable></View></ReplySwipe>;}}/>
  {transfers.selections.filter(s=>s.group?.id===route.params.id).map(s=><View key={s.id} style={{padding:8}}><Text style={{color:colors.textSecondary}}>{s.name} · {s.failed?'Could not prepare attachment':'Preparing attachment…'}</Text>{s.failed&&<View style={{flexDirection:'row',gap:20}}><Pressable onPress={()=>void retryRootAttachmentSelection(s.id).catch(report)}><Text style={{color:colors.primary}}>Retry</Text></Pressable><Pressable onPress={()=>void removeRootAttachmentSelection(s.id).catch(report)}><Text style={{color:colors.primary}}>Remove</Text></Pressable></View>}</View>)}
  {menu&&<RootMessageMenu message={menu} close={()=>setMenu(undefined)} copy={()=>void Clipboard.setStringAsync(menu.text).catch(report)} reply={()=>{setEditing(undefined);setReply(target(menu));}} edit={()=>{setReply(undefined);setEditing(menu);setText(menu.text);}} remove={()=>Alert.alert('Delete message?','Group members will see a deleted-message placeholder.',[{text:'Cancel',style:'cancel'},{text:'Delete',style:'destructive',onPress:()=>void act(menu,'delete')}])} react={value=>void act(menu,'reaction',value)}/>}
  {(reply||editing)&&<View style={{padding:12,flexDirection:'row',gap:12,backgroundColor:colors.surface}}><Text style={{color:colors.text,flex:1}} numberOfLines={2}>{editing?'Editing: '+editing.text:'Replying: '+(messages.find(q=>q.group?.messageId===reply!.id&&(q.direction==='outgoing'?owner:q.peer)===reply!.author)?.text??'Original message')}</Text><Pressable accessibilityLabel="Cancel group reply or edit" onPress={()=>{setReply(undefined);if(editing)setText('');setEditing(undefined);}}><Text style={{color:colors.primary}}>Cancel</Text></Pressable></View>}
  <AttachmentMenu visible={attach} onClose={()=>setAttach(false)} onCamera={()=>void work(()=>pickRootGroupMedia(route.params.id,'camera'))} onMultimedia={()=>void work(()=>pickRootGroupMedia(route.params.id,'library'))} onFiles={()=>void work(()=>pickRootGroupAttachment(route.params.id))}/>
  {stickers&&owner&&<StickerPicker ownerId={owner} draftStorage={rootStickerDraft(owner)} onClose={()=>setStickers(false)} onSend={s=>work(async()=>{await messaging.sendGroupText(route.params.id,stickerMessage(s),undefined,owner);})} onSendImported={s=>work(async()=>{const uri=importedStickerUri(owner,s);return queueRootGroupAttachmentSource(await rootGroupAttachmentAudience(route.params.id),uri,IMPORTED_STICKER_CONTENT,await stickerFileMime(uri));})}/>}
  <View style={[styles.inputBar,{backgroundColor:colors.chatBg,borderTopColor:colors.neonBorder,paddingBottom:Math.max(insets.bottom,8)}]}><View style={styles.inputRowWrap}>{!voice&&<><TouchableOpacity accessibilityLabel="Attach" disabled={disabled||!!reply||!!editing} onPress={()=>setAttach(true)} style={[styles.attachBtn,{borderColor:colors.neonBorder,backgroundColor:colors.surface,shadowColor:colors.primary}]}><Ionicons name="add" size={25} color={colors.primary}/></TouchableOpacity><View style={[styles.inputRow,{backgroundColor:colors.surface,borderColor:colors.neonBorder,paddingLeft:12}]}><Pressable accessibilityLabel="Open stickers" disabled={disabled||!!reply||!!editing} onPress={()=>setStickers(true)} style={{padding:8}}><Ionicons name="happy-outline" size={24} color={colors.primary}/></Pressable><TextInput accessibilityLabel="New group message" placeholder="Compose message…" placeholderTextColor={colors.textTertiary} value={text} onChangeText={setText} multiline editable={!disabled} maxLength={1600} style={[styles.textInput,{color:colors.text}]}/></View></>}{text.trim()?<TouchableOpacity accessibilityLabel="Send group message" disabled={disabled} onPress={()=>void send(text)} style={[styles.sendBtn,{backgroundColor:colors.primary,opacity:disabled?0.45:1}]}><Text style={{color:colors.textInverse}}>▶</Text></TouchableOpacity>:<RootVoiceComposer peer={route.params.id} groupId={route.params.id} disabled={disabled||!!reply||!!editing} onActive={setVoice} onError={report}/>}</View></View>
 </KeyboardAvoidingView>;
}
