import { StyleSheet } from 'react-native';
import { Font, Spacing, Radius } from '../../theme';

export const profileStyles = StyleSheet.create({
  container: { flex: 1 },
  content: { paddingBottom: Spacing.xxl },
  identityCard: { marginTop: Spacing.sm },
  identityRow: { flexDirection: 'row', alignItems: 'center', gap: Spacing.sm },
  identityAvatarColumn: { flex: 1, minWidth: 0, alignItems: 'center' },
  identityQrColumn: { flex: 1, minWidth: 0, alignItems: 'center' },
  identityUsername: { textAlign: 'center', letterSpacing: 1 },
  identityCaption: { textAlign: 'center' },
  identityQrBox: { padding: 8, borderWidth: 1, borderRadius: Radius.sm },
  identityStatus: { alignSelf: 'center', marginTop: Spacing.md },
  expandedQrScreen: { flex: 1, alignItems: 'center', justifyContent: 'center' },
  expandedQrBox: { padding: 16, backgroundColor: '#fff', borderRadius: Radius.md },

  mediaSetupNotice: {
    marginHorizontal: Spacing.sm,
    marginTop: Spacing.sm,
    marginBottom: Spacing.sm,
    padding: Spacing.lg,
    borderRadius: Radius.lg,
    borderWidth: 1.5,
    shadowOpacity: 0.22,
    shadowRadius: 10,
    shadowOffset: { width: 0, height: 0 },
    elevation: 3,
  },
  mediaSetupHeading: {
    flexDirection: 'row',
    alignItems: 'flex-start',
    gap: Spacing.md,
  },
  mediaSetupIcon: {
    width: 44,
    height: 44,
    borderRadius: Radius.md,
    borderWidth: 1,
    alignItems: 'center',
    justifyContent: 'center',
  },
  mediaSetupCopy: { flex: 1 },
  mediaSetupTitle: {
    fontSize: Font.size.sm,
    fontWeight: '800',
    letterSpacing: 1,
  },
  mediaSetupDescription: {
    fontSize: Font.size.sm,
    lineHeight: 19,
    marginTop: Spacing.xs,
  },
  mediaSetupButton: { marginTop: Spacing.md },

  avatarSection: {
    alignItems: 'center',
    paddingVertical: Spacing.xl,
    marginBottom: Spacing.sm,
    borderBottomWidth: 1,
  },
  avatarEditBadge: {
    position: 'absolute',
    bottom: 0,
    right: 0,
    width: 28,
    height: 28,
    borderRadius: 14,
    borderWidth: 1.5,
    alignItems: 'center',
    justifyContent: 'center',
    shadowOpacity: 0.6,
    shadowRadius: 6,
    shadowOffset: { width: 0, height: 0 },
  },
  username: { fontSize: Font.size.xl, marginTop: Spacing.md, fontWeight: '800', letterSpacing: 3 },
  email: { fontSize: Font.size.sm, marginTop: Spacing.xs, letterSpacing: 0.5 },
  statusBadge: {
    flexDirection: 'row',
    alignItems: 'center',
    marginTop: Spacing.sm,
    paddingHorizontal: Spacing.md,
    paddingVertical: Spacing.xs,
    borderRadius: Radius.sm,
    borderWidth: 1,
    shadowOpacity: 0.6,
    shadowRadius: 6,
    shadowOffset: { width: 0, height: 0 },
  },
  statusDot: {
    width: 7,
    height: 7,
    borderRadius: 3.5,
    marginRight: Spacing.xs,
    shadowOpacity: 0.9,
    shadowRadius: 4,
    shadowOffset: { width: 0, height: 0 },
  },
  statusText: { fontSize: Font.size.xs, fontWeight: '700', letterSpacing: 1.5 },

  card: {
    paddingHorizontal: Spacing.lg,
    paddingTop: Spacing.lg,
    paddingBottom: Spacing.md,
    marginBottom: Spacing.sm,
    borderRadius: Radius.md,
    marginHorizontal: Spacing.sm,
    borderWidth: 1,
  },
  cardTitle: { fontSize: Font.size.xs, fontWeight: '700', letterSpacing: 1.5, marginBottom: Spacing.md },
  label: { fontSize: Font.size.xs, fontWeight: '700', letterSpacing: 1, marginBottom: Spacing.xs },
  saveBtn: {
    marginTop: Spacing.sm,
    borderRadius: Radius.md,
  },
  tagBox: {
    flexDirection: 'row',
    alignItems: 'center',
    marginTop: Spacing.md,
    paddingHorizontal: Spacing.md,
    paddingVertical: Spacing.md,
    borderRadius: Radius.md,
    borderWidth: 1,
    shadowOpacity: 0.25,
    shadowRadius: 8,
    shadowOffset: { width: 0, height: 0 },
    elevation: 3,
  },
  tagValue: {
    fontSize: Font.size.lg,
    fontWeight: '800',
    letterSpacing: 3,
  },
  tagHint: {
    fontSize: Font.size.xs,
    marginTop: 4,
    letterSpacing: 0.5,
  },
  qrBox: {
    alignSelf: 'center',
    marginTop: Spacing.lg,
    padding: Spacing.md,
    borderRadius: Radius.md,
    borderWidth: 1,
  },
  qrHint: {
    fontSize: Font.size.xs,
    textAlign: 'center',
    marginTop: Spacing.sm,
    letterSpacing: 0.5,
  },

  infoRow: {
    flexDirection: 'row',
    justifyContent: 'space-between',
    paddingVertical: Spacing.md,
    borderBottomWidth: 1,
  },
  infoLabel: { fontSize: Font.size.sm, letterSpacing: 1, fontWeight: '600' },
  infoValue: { fontSize: Font.size.sm, fontWeight: '500' },

  actionRow: {
    flexDirection: 'row',
    alignItems: 'center',
    justifyContent: 'space-between',
    paddingVertical: Spacing.md,
  },
  actionLeft: { flexDirection: 'row', alignItems: 'center', flex: 1 },
  actionLabel: { fontSize: Font.size.sm, fontWeight: '700', letterSpacing: 1 },

  toggleRow: {
    flexDirection: 'row',
    alignItems: 'center',
    justifyContent: 'space-between',
    paddingVertical: Spacing.md,
  },
  toggleLabel: { fontSize: Font.size.sm, fontWeight: '700', letterSpacing: 1 },
  toggleDesc: { fontSize: Font.size.xs, marginTop: 2, letterSpacing: 0.2 },

  logoutBtn: {
    marginTop: Spacing.md,
    marginHorizontal: Spacing.lg,
    paddingVertical: Spacing.lg,
    alignItems: 'center',
    borderRadius: Radius.md,
    borderWidth: 1.5,
    shadowOpacity: 0.35,
    shadowRadius: 8,
    shadowOffset: { width: 0, height: 0 },
  },
  logoutText: { fontSize: Font.size.sm, fontWeight: '800', letterSpacing: 2 },

  deleteBtn: {
    marginTop: Spacing.sm,
    marginHorizontal: Spacing.lg,
    paddingVertical: Spacing.md,
    alignItems: 'center',
    borderRadius: Radius.sm,
    borderWidth: 1,
    borderStyle: 'dashed',
  },
  deleteText: { fontSize: Font.size.xs, fontWeight: '700', letterSpacing: 1.5 },

  versionText: {
    textAlign: 'center',
    marginTop: Spacing.lg,
    marginBottom: Spacing.md,
    fontSize: Font.size.xs,
    letterSpacing: 1,
  },

  themeRow: {
    flexDirection: 'row',
    gap: Spacing.sm,
    marginBottom: Spacing.md,
  },
  themeOption: {
    flex: 1,
    alignItems: 'center',
    paddingVertical: Spacing.md,
    borderRadius: Radius.sm,
    borderWidth: 1.5,
    shadowOpacity: 0.4,
    shadowRadius: 6,
    shadowOffset: { width: 0, height: 0 },
  },
  themeLabel: {
    fontSize: Font.size.xs,
    fontWeight: '700',
    letterSpacing: 1,
  },

  connectivityDesc: {
    fontSize: Font.size.sm,
    lineHeight: 20,
    marginBottom: Spacing.md,
    letterSpacing: 0.2,
  },
  connectivityRow: {
    flexDirection: 'row',
    gap: Spacing.sm,
    marginBottom: Spacing.md,
  },
  connectivityOption: {
    flex: 1,
    alignItems: 'center',
    paddingVertical: Spacing.md,
    borderRadius: Radius.sm,
    borderWidth: 1.5,
    shadowOpacity: 0.4,
    shadowRadius: 6,
    shadowOffset: { width: 0, height: 0 },
  },
  connectivityLabel: {
    fontSize: Font.size.xs,
    fontWeight: '700',
    letterSpacing: 1,
    textAlign: 'center',
  },
  connectivitySubLabel: {
    fontSize: Font.size.xs,
    marginTop: 2,
    textAlign: 'center',
    letterSpacing: 0.3,
  },
});

